using System;
using System.Collections.Generic;
using UnityEngine;

namespace StableDiffusion
{
    // this will act as a container for the images generated by the sdApi that can be used by multiple components
    [CreateAssetMenu(fileName = "SdRenderTarget", menuName = "StableDiffusion/RenderTarget", order = 1)]
    public class SdRenderTargetSo : ScriptableObject
    {
        //images set eventhandler, using unity events for inspector compatibility
        public event Action<List<Texture2D>> OnImagesSet;
        public List<Texture2D> images;

        public virtual void SetImages(List<Texture2D> images)
        {
            this.images = images;
            OnImagesSet?.Invoke(images);
        }
    }

}